package org.xjb.cxf.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-28T21:41:40.176+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://ws.cxf.xjb.org/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllCats", targetNamespace = "http://ws.cxf.xjb.org/", className = "org.xjb.cxf.ws.GetAllCats")
    @WebMethod
    @ResponseWrapper(localName = "getAllCatsResponse", targetNamespace = "http://ws.cxf.xjb.org/", className = "org.xjb.cxf.ws.GetAllCatsResponse")
    public org.xjb.cxf.ws.StringCat getAllCats();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://ws.cxf.xjb.org/", className = "org.xjb.cxf.ws.SayHi")
    @WebMethod
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://ws.cxf.xjb.org/", className = "org.xjb.cxf.ws.SayHiResponse")
    public java.lang.String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCatByUser", targetNamespace = "http://ws.cxf.xjb.org/", className = "org.xjb.cxf.ws.GetCatByUser")
    @WebMethod
    @ResponseWrapper(localName = "getCatByUserResponse", targetNamespace = "http://ws.cxf.xjb.org/", className = "org.xjb.cxf.ws.GetCatByUserResponse")
    public java.util.List<org.xjb.cxf.ws.Cat> getCatByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        org.xjb.cxf.ws.User arg0
    );
}
