package org.xjb.cxf.ws.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import org.xjb.cxf.ws.HelloWorld;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-28T14:57:33.453+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "HelloWorldService", 
                  wsdlLocation = "http://192.168.1.101:7070/hw?wsdl",
                  targetNamespace = "http://impl.ws.cxf.xjb.org/") 
public class HelloWorldService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.cxf.xjb.org/", "HelloWorldService");
    public final static QName HelloworldImplPort = new QName("http://impl.ws.cxf.xjb.org/", "HelloworldImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.1.101:7070/hw?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWorldService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.1.101:7070/hw?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWorldService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWorldService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HelloWorldService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloWorldService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloWorldService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "HelloworldImplPort")
    public HelloWorld getHelloworldImplPort() {
        return super.getPort(HelloworldImplPort, HelloWorld.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "HelloworldImplPort")
    public HelloWorld getHelloworldImplPort(WebServiceFeature... features) {
        return super.getPort(HelloworldImplPort, HelloWorld.class, features);
    }

}
